Repository SmartCity-2022/Service-Bildungsportal, pull requests merged in 2022-06, with the labels that each got.

#41 Authorisierung / Authentifizierung über das MainHub
  README.md
  backend/build.gradle.kts
  backend/src/main/kotlin/com/smartcity/education/backend/BackendApplication.kt
  backend/src/main/kotlin/com/smartcity/education/backend/Constants.kt
  backend/src/main/kotlin/com/smartcity/education/backend/SecurityConfig.kt
  backend/src/main/kotlin/com/smartcity/education/backend/authentication/AuthUtil.kt
  backend/src/main/kotlin/com/smartcity/education/backend/authentication/JwtFilter.kt
  backend/src/main/kotlin/com/smartcity/education/backend/authentication/TokenVerifier.kt
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/EducationApiController.kt
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/InstitutionApiController.kt
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/LocationApiController.kt
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/StudentApiController.kt
  backend/src/main/kotlin/com/smartcity/education/backend/models/User.kt
  backend/src/main/kotlin/com/smartcity/education/backend/repositories/UserRepository.kt
  backend/src/main/resources/application.properties
  backend/src/test/kotlin/com/smartcity/education/backend/authentication/JwtFilterTest.kt
  backend/src/test/kotlin/com/smartcity/education/backend/authentication/TokenVerifierTest.kt
  backend/src/test/kotlin/com/smartcity/education/backend/controllers/EducationApiControllerTests.kt
  backend/src/test/kotlin/com/smartcity/education/backend/controllers/InstitutionApiControllerTests.kt
  backend/src/test/kotlin/com/smartcity/education/backend/controllers/LocationApiControllerTests.kt
  backend/src/test/kotlin/com/smartcity/education/backend/controllers/StudentApiControllerTests.kt
  doc/openapi.yaml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/api.ts
  frontend/src/index.tsx
Labels: minor

#46 declare exchange as durable
  backend/src/main/kotlin/com/smartcity/education/backend/RabbitMqConfig.kt
Labels: patch

#50 use correct mainhub token endpoint
  frontend/src/index.tsx
Labels: patch

#49 refactoring: replace field injection with constructor injection
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/EducationApiController.kt
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/InstitutionApiController.kt
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/LocationApiController.kt
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/QualificationApiController.kt
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/StudentApiController.kt
  backend/src/test/kotlin/com/smartcity/education/backend/controllers/QualificationApiControllerTests.kt
Labels: skip-release

#48 integration tests
  README.md
  test/cypress/cypress.config.js
  test/cypress/cypress/e2e/EducationDetails.cy.js
  test/cypress/cypress/e2e/InstitutionDetails.cy.js
  test/cypress/cypress/fixtures/example.json
  test/cypress/cypress/support/commands.js
  test/cypress/cypress/support/e2e.js
  test/cypress/package-lock.json
  test/cypress/package.json
  test/db/init.sql
Labels: skip-release

#53 Token Refresh Proxy
  README.md
  backend/src/main/kotlin/com/smartcity/education/backend/BackendApplication.kt
  backend/src/main/kotlin/com/smartcity/education/backend/Constants.kt
  backend/src/main/kotlin/com/smartcity/education/backend/SecurityConfig.kt
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/TokenApiController.kt
  backend/src/main/kotlin/com/smartcity/education/backend/models/AccessToken.kt
  backend/src/main/kotlin/com/smartcity/education/backend/models/RefreshToken.kt
  frontend/src/index.tsx
Labels: patch

#55 extend test cases of me controller
  backend/src/test/kotlin/com/smartcity/education/backend/controllers/MeApiControllerTests.kt
Labels: patch

#58 Implementierung des Grade-Controllers
  backend/src/main/kotlin/com/smartcity/education/backend/assigners/GradeAssigner.kt
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/GradeApiController.kt
  backend/src/main/kotlin/com/smartcity/education/backend/models/Grade.kt
  backend/src/main/kotlin/com/smartcity/education/backend/models/GradeProperties.kt
  backend/src/main/kotlin/com/smartcity/education/backend/repositories/GradeRepository.kt
  backend/src/test/kotlin/com/smartcity/education/backend/assigners/GradeAssignerTest.kt
  backend/src/test/kotlin/com/smartcity/education/backend/controllers/GradeApiControllerTests.kt
Labels: minor

#59 Implementierung des Graduation-Controllers
  backend/src/main/kotlin/com/smartcity/education/backend/assigners/GraduationAssigner.kt
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/GraduationApiController.kt
  backend/src/main/kotlin/com/smartcity/education/backend/models/Graduation.kt
  backend/src/main/kotlin/com/smartcity/education/backend/models/GraduationProperties.kt
  backend/src/main/kotlin/com/smartcity/education/backend/repositories/GraduationRepository.kt
  backend/src/test/kotlin/com/smartcity/education/backend/assigners/GraduationAssignerTest.kt
  backend/src/test/kotlin/com/smartcity/education/backend/controllers/GraduationApiControllerTests.kt
  doc/openapi.yaml
Labels: minor

#60 Implementierung des Matriculation-Controllers
  backend/src/main/kotlin/com/smartcity/education/backend/assigners/MatriculationAssigner.kt
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/MatriculationApiController.kt
  backend/src/main/kotlin/com/smartcity/education/backend/models/Matriculation.kt
  backend/src/main/kotlin/com/smartcity/education/backend/models/MatriculationProperties.kt
  backend/src/test/kotlin/com/smartcity/education/backend/assigners/MatriculationAssignerTest.kt
  backend/src/test/kotlin/com/smartcity/education/backend/controllers/MatriculationApiControllerTests.kt
  frontend/tsconfig.json
Labels: minor

#61 assessment overview
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/AssessmentApiController.kt
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/MatriculationApiController.kt
  backend/src/main/kotlin/com/smartcity/education/backend/models/Grade.kt
  frontend/src/AssessmentList.tsx
  frontend/src/AssessmentOverview.tsx
  frontend/src/api/api.ts
  frontend/src/common.css
  frontend/src/index.tsx
Labels: minor

#63 add new dependency to test
  backend/src/test/kotlin/com/smartcity/education/backend/controllers/AssessmentApiControllerTests.kt
  backend/src/test/kotlin/com/smartcity/education/backend/controllers/MatriculationApiControllerTests.kt
Labels: patch

#66 Implementierung fehlender RabbitMQ Events
  backend/src/main/kotlin/com/smartcity/education/backend/Constants.kt
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/EducationApiController.kt
  backend/src/main/kotlin/com/smartcity/education/backend/controllers/MatriculationApiController.kt
Labels: patch

#64 Erstellung eines neuen Bildungsangebots
  frontend/src/EducationCreation.tsx
  frontend/src/EducationDetails.tsx
  frontend/src/Header.tsx
  frontend/src/Resources.ts
  frontend/src/common.css
  frontend/src/index.tsx
Labels: minor

#67 add missing dependency to test
  backend/src/test/kotlin/com/smartcity/education/backend/controllers/EducationApiControllerTests.kt
  backend/src/test/kotlin/com/smartcity/education/backend/controllers/MatriculationApiControllerTests.kt
Labels: patch

#72 frontend: show icon next to education if graduated
  frontend/src/AssessmentList.tsx
  frontend/src/AssessmentOverview.tsx
  frontend/src/common.css
Labels: minor

#73 Update common.css
  frontend/src/common.css
Labels: patch

#74 "Kleinigkeiten" für das Release
  README.md
  backend/src/main/kotlin/com/smartcity/education/backend/models/User.kt
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
Labels: major

#69 frontend: introduce registration page
  frontend/src/EducationCreation.tsx
  frontend/src/EducationDetails.tsx
  frontend/src/Header.tsx
  frontend/src/RegisterStudent.tsx
  frontend/src/Resources.ts
  frontend/src/Util.ts
  frontend/src/common.css
  frontend/src/index.tsx
Labels: minor
